oe_webtools_analytics.settings:
  type: config_object
  label: 'Webtools Analytics settings'
  mapping:
    siteID:
      type: string
      label: 'Site ID'
      description: 'The site universal unique identifier.'
    sitePath:
      type: string
      label: 'Site path'
      description: 'The domain + root path without protocol.'
    instance:
      type: string
      label: 'Instance'
      description: 'The server instance. e.g. testing, ec.europa.eu or europa.eu.'
