oe_webtools_hotjar.settings:
  type: config_object
  label: 'Webtools Hotjar settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    site:
      type: string
      label: 'Site ID'
